{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.eimzo",
    "module": "eimzo-sdk",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-2.1.0.aar",
          "url": "eimzo-sdk-2.1.0.aar",
          "size": 12827573,
          "sha512": "e93aa0278f2b6e20b5603d7ea300b85f5d1974a8f86dd681a889da38f0b29a652eee0b89ae219677a11dfe55c53ae5b66990ed4f18480fcfd2db31fce6ca95a8",
          "sha256": "240ae0be302d1f73c922600cd29f00e1fba8226508af9589ac1e06a0fa2d8aae",
          "sha1": "e5ec36d06e3cdb7319a297125fd68cea7fccb814",
          "md5": "cb61f282f87e7846a3dbecdbca6695d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-2.1.0.aar",
          "url": "eimzo-sdk-2.1.0.aar",
          "size": 12827573,
          "sha512": "e93aa0278f2b6e20b5603d7ea300b85f5d1974a8f86dd681a889da38f0b29a652eee0b89ae219677a11dfe55c53ae5b66990ed4f18480fcfd2db31fce6ca95a8",
          "sha256": "240ae0be302d1f73c922600cd29f00e1fba8226508af9589ac1e06a0fa2d8aae",
          "sha1": "e5ec36d06e3cdb7319a297125fd68cea7fccb814",
          "md5": "cb61f282f87e7846a3dbecdbca6695d3"
        }
      ]
    }
  ]
}
