{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.eimzo",
    "module": "eimzo-sdk",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-1.2.7.aar",
          "url": "eimzo-sdk-1.2.7.aar",
          "size": 11589701,
          "sha512": "631837572efe37f44a4c8d4240d92019b0b4baafe87312900e7a86278af4eda5fce48d52e2d7270b8e4c0bbca3e8660f11c325c5120b306671d06483f806e6bf",
          "sha256": "2f71873bebcfae3655f62d633df3e39f88881abf31a5fd7f60c54bf17221703d",
          "sha1": "299efc458be58a5b1063f05c502c2840bb9f85c1",
          "md5": "4aee0dbdee46319fbbc1356a975b9f27"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-1.2.7.aar",
          "url": "eimzo-sdk-1.2.7.aar",
          "size": 11589701,
          "sha512": "631837572efe37f44a4c8d4240d92019b0b4baafe87312900e7a86278af4eda5fce48d52e2d7270b8e4c0bbca3e8660f11c325c5120b306671d06483f806e6bf",
          "sha256": "2f71873bebcfae3655f62d633df3e39f88881abf31a5fd7f60c54bf17221703d",
          "sha1": "299efc458be58a5b1063f05c502c2840bb9f85c1",
          "md5": "4aee0dbdee46319fbbc1356a975b9f27"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "eimzo-sdk-1.2.7-sources.jar",
          "url": "eimzo-sdk-1.2.7-sources.jar",
          "size": 141810,
          "sha512": "8ade4f2d5a4e8343ae2f975f5677f93ecd62673fa12a00fbf769cf95849713ba92d9816d622769ad6f4bb424ec35037dc17f4878b3e58354e7616e65ff0df10d",
          "sha256": "8a065eb8d0c34afce65e21eabc17e6fbdf0e382f5c89336ff73d09c2b1b3915f",
          "sha1": "d68066b496d68bb173dd3190d891f493b296b39a",
          "md5": "10ec7bd8d984bc6e36db26d02f093911"
        }
      ]
    }
  ]
}
