{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.eimzo",
    "module": "eimzo-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-1.0.2.aar",
          "url": "eimzo-sdk-1.0.2.aar",
          "size": 997720,
          "sha512": "65828e80b47e2996340c53de2fafd5075922121b69ae918c7f8ea8cd9f3ebee344d1b94b588781d4edac05d36c974566b6f8b4b7c37188238a9c059a9d1ee750",
          "sha256": "fdab42052564e5b9e5797fae82099eea3aeefa7329aadc5fea63e5d519f05b83",
          "sha1": "ed34b1d7a4fc7baa659a6c0956aafe06d4dbd72e",
          "md5": "46618902d33adc380554515a67063bdb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uz.yt",
          "module": "pfx2qr",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-1.0.2.aar",
          "url": "eimzo-sdk-1.0.2.aar",
          "size": 997720,
          "sha512": "65828e80b47e2996340c53de2fafd5075922121b69ae918c7f8ea8cd9f3ebee344d1b94b588781d4edac05d36c974566b6f8b4b7c37188238a9c059a9d1ee750",
          "sha256": "fdab42052564e5b9e5797fae82099eea3aeefa7329aadc5fea63e5d519f05b83",
          "sha1": "ed34b1d7a4fc7baa659a6c0956aafe06d4dbd72e",
          "md5": "46618902d33adc380554515a67063bdb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "eimzo-sdk-1.0.2-sources.jar",
          "url": "eimzo-sdk-1.0.2-sources.jar",
          "size": 120606,
          "sha512": "8d261cb7cb55df8d0d97f2ce7d7eb5251ef1a54113d6ae738b06c8c75364c08e7211e00e76bd9c24c01628519d1724140f17c5805565eb58a1d3384cfbac25db",
          "sha256": "87a10a019dc913e59435f48ed65aef12e02820b36ee05325b756c492b2becbe6",
          "sha1": "c0c3110fc2ead49ce635dcb7b007941afc84540e",
          "md5": "1fb168b76ddaab629db78f4185e8c6c0"
        }
      ]
    }
  ]
}
