{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.eimzo",
    "module": "eimzo-sdk",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-2.2.1.aar",
          "url": "eimzo-sdk-2.2.1.aar",
          "size": 12922256,
          "sha512": "e453588e5f80f73a06a850a2565fbe4e0c7a0a6f1080d17fd625ba816ab77b622264ae74fd8383f1e42fde2a4ec0b1573954c12bb695f50b943f820174aa67a1",
          "sha256": "6f13bb07bfdaf4e0fc2a2eb146a6f3ea1d99cf66c3d0d8b8795289abb0d87d83",
          "sha1": "572d02289da5bd1f56491c2cea20042ea0329930",
          "md5": "2c69f78189088b81d9e4e14320f87b8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-2.2.1.aar",
          "url": "eimzo-sdk-2.2.1.aar",
          "size": 12922256,
          "sha512": "e453588e5f80f73a06a850a2565fbe4e0c7a0a6f1080d17fd625ba816ab77b622264ae74fd8383f1e42fde2a4ec0b1573954c12bb695f50b943f820174aa67a1",
          "sha256": "6f13bb07bfdaf4e0fc2a2eb146a6f3ea1d99cf66c3d0d8b8795289abb0d87d83",
          "sha1": "572d02289da5bd1f56491c2cea20042ea0329930",
          "md5": "2c69f78189088b81d9e4e14320f87b8c"
        }
      ]
    }
  ]
}
