{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.eimzo",
    "module": "eimzo-sdk",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-1.2.2.aar",
          "url": "eimzo-sdk-1.2.2.aar",
          "size": 1013134,
          "sha512": "b1e6f8febab534a4e306893de4fab44314af1e65ae224ce976ffa55b916c36ba254634c64b7bf88a179ac304e813dc9dd9c0c844cd2929c98c994887bd359023",
          "sha256": "5835b8a8c3faa856668b801de6a5ba8d7bc6497f4eae73ebfab200bc7bbb2cae",
          "sha1": "eb71b7af279e9ae3f6fcdf70619be576c8957694",
          "md5": "a1b6b0e501823624fd20750b97bda415"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uz.yt",
          "module": "pfx2qr",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-1.2.2.aar",
          "url": "eimzo-sdk-1.2.2.aar",
          "size": 1013134,
          "sha512": "b1e6f8febab534a4e306893de4fab44314af1e65ae224ce976ffa55b916c36ba254634c64b7bf88a179ac304e813dc9dd9c0c844cd2929c98c994887bd359023",
          "sha256": "5835b8a8c3faa856668b801de6a5ba8d7bc6497f4eae73ebfab200bc7bbb2cae",
          "sha1": "eb71b7af279e9ae3f6fcdf70619be576c8957694",
          "md5": "a1b6b0e501823624fd20750b97bda415"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "eimzo-sdk-1.2.2-sources.jar",
          "url": "eimzo-sdk-1.2.2-sources.jar",
          "size": 130582,
          "sha512": "52f0fd2e95450343fd9058d8669c303582b55b618baca9a7d9479f6ff07b5deb59ca1f05d686f211085b69709d42eca30babd77f5aaec4414debd430b88ea3f1",
          "sha256": "adbda817ee68a491dbd7cd01f8b7082cce969aa05199e7b8dcce8ee97e70a1bb",
          "sha1": "391902d5f55aa5972316bb19a3298bc1d7170bd8",
          "md5": "ec474f8fdac4dc3ebe0f95a9daeb07ad"
        }
      ]
    }
  ]
}
