{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.eimzo",
    "module": "eimzo-sdk",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-2.1.1.aar",
          "url": "eimzo-sdk-2.1.1.aar",
          "size": 12827633,
          "sha512": "bc88148066c38a2528eb7f611ac76c7c7c08f1b94fcf71391197d737d3990a20f5fe87e8249a82f49e81b0108e328a27041311b04c7513aea2e93a5d0b3edeef",
          "sha256": "5f6af0b9c83ba8923f2e83c01fd09845410e107f02fb89e96c4e3016ad38a557",
          "sha1": "cdf949fb9103cc3726f786a19409779158b0251b",
          "md5": "8b7b2e505384c73a8e66bc1d8ab5b874"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "eimzo-sdk-2.1.1.aar",
          "url": "eimzo-sdk-2.1.1.aar",
          "size": 12827633,
          "sha512": "bc88148066c38a2528eb7f611ac76c7c7c08f1b94fcf71391197d737d3990a20f5fe87e8249a82f49e81b0108e328a27041311b04c7513aea2e93a5d0b3edeef",
          "sha256": "5f6af0b9c83ba8923f2e83c01fd09845410e107f02fb89e96c4e3016ad38a557",
          "sha1": "cdf949fb9103cc3726f786a19409779158b0251b",
          "md5": "8b7b2e505384c73a8e66bc1d8ab5b874"
        }
      ]
    }
  ]
}
